name: Compile Schemas
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install compiletojsonschema==0.3.0
    - name: Compile Assessment Methods
      run: "compiletojsonschema --codelist-base-directory schema/codelists schema/assessment_resource.json"
